import pipeline from './index'
import basicTheme from '../test/theme'
import { VERSION } from '@airtheme/core'

test('builds theme object', () => {
  const result = pipeline(basicTheme)
  result.id = 'test_id' // Since autogenerated

  expect(result).toEqual({
    baseFontSize: '16px',
    baseLineHeight: '18.4px',
    baseSpacing: '16px',
    fontFace: {
      'Andale Mono': 'Andale Mono',
      'Arial Black': 'Arial Black',
      Helvetica: 'Helvetica'
    },
    id: 'test_id',
    name: 'My Awesome Theme',
    setting: {
      color: { ltGrey: '#bfd7ea', primary: '#0b3954', secondary: '#ff6663' },
      fontFamily: {
        body: 'Helvetica',
        code: 'Andale Mono',
        title: 'Helvetica'
      },
      fontSize: { lg: '17.6px', md: '16px', sm: '14.4px' },
      fontWeight: { dk: '700', lt: '300', md: '500' },
      spacing: { lg: '24px', md: '16px', sm: '8px' }
    },
    swatch: {
      'pale aqua': '#bfd7ea',
      'pastel red': '#ff6663',
      'prussian blue': '#0b3954'
    },
    version: '0.1.0'
  })

  expect(true).toEqual(true)
})
