import pipeline from './index'
import basicTheme from '../test/theme'
import { VERSION } from '@airtheme/core'

test('builds theme object', () => {
  const result = pipeline(basicTheme)
  result.id = 'test_id' // Since autogenerated

  expect(result).toEqual({
    id: 'test_id',
    name: 'Test Theme',
    version: VERSION,
    baseFontSize: { baseFontSize: '16px' },
    baseLineHeight: { baseLineHeight: '18.4px' },
    baseSpacing: { baseSpacing: '16px' },
    setting: {
      color: { ltGrey: '#bfd7ea', primary: '#0b3954', secondary: '#ff6663' },
      fontFamily: {
        body: 'Helvetica',
        code: 'Andale Mono',
        title: 'Helvetica'
      },
      fontSize: { lg: '17.6px', md: '16px', sm: '14.4px' },
      fontWeight: { dk: '700', lt: '300', md: '500' },
      spacing: { lg: '24px', md: '16px', sm: '8px' }
    }
  })

  expect(true).toEqual(true)
})
