import {
  BASE_FONT_SIZE_KEY,
  BASE_LINE_HEIGHT_KEY,
  BASE_SPACING_KEY,
  COLOR_KEY,
  FONT_FAMILY_KEY,
  FONT_SIZE_KEY,
  FONT_WEIGHT_KEY,
  SETTING_KEY,
  BASE_KEY,
  SPACING_KEY,
  SWATCH_KEY,
  UTILITY_KEY
} from './themeKeys'

export const BASE_FONT_SIZE_PATH = `${BASE_KEY}.${BASE_FONT_SIZE_KEY}`
export const BASE_LINE_HEIGHT_PATH = BASE_LINE_HEIGHT_KEY
export const BASE_SPACING_PATH = BASE_SPACING_KEY
export const COLOR_PATH = `${SETTING_KEY}.${COLOR_KEY}`
export const FONT_FAMILY_PATH = `${SETTING_KEY}.${FONT_FAMILY_KEY}`
export const FONT_SIZE_PATH = `${SETTING_KEY}.${FONT_SIZE_KEY}`
export const FONT_WEIGHT_PATH = `${SETTING_KEY}.${FONT_WEIGHT_KEY}`
export const SETTING_PATH = SETTING_KEY
export const SPACING_PATH = `${SETTING_KEY}.${SPACING_KEY}`
export const SWATCH_PATH = SWATCH_KEY
export const UTILITY_PATH = UTILITY_KEY
