export const ADD_FONT_FAMILY = 'ADD_FONT_FAMILY'
export const REMOVE_FONT_FAMILY = 'REMOVE_FONT_FAMILY'
export const UPDATE_FONT_FAMILY = 'UPDATE_FONT_FAMILY'
export const UPDATE_FONT_FAMILY_VIEW = 'UPDATE_FONT_FAMILY_VIEW'
