export const ADD_FONT_SIZE = 'ADD_FONT_SIZE'
export const REMOVE_FONT_SIZE = 'REMOVE_FONT_SIZE'
export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE'
export const UPDATE_FONT_SIZE_VIEW = 'UPDATE_FONT_SIZE_VIEW'
