export { default as GlobalsInfo } from './Info/Globals'
export { default as SwatchInfo } from './Info/Swatch'
export { default as FontFaceInfo } from './Info/FontFace'
export { default as FontFamilyInfo } from './Info/FontFamily'
export { default as FontSizeInfo } from './Info/FontSize'
export { default as FontWeightInfo } from './Info/FontWeight'
export { default as ColorInfo } from './Info/Color'
export { default as SpacingInfo } from './Info/Spacing'
export { default as BaseFontSizeInfo } from './Info/BaseFontSize'
export { default as BaseLineHeightInfo } from './Info/BaseLineHeight'
export { default as BaseSpacingInfo } from './Info/BaseSpacing'

// Specimen
export { default as SpecimenBaseFont } from './Specimen/BaseFont'
export { default as SpecimenFontWeight } from './Specimen/FontWeight'
export { default as Typography } from './Specimen/Typography'
