// @flow

import ifRuleFor from './lib/ifRuleFor'

import type { props, unitValue, unitKey } from './flow/types'

export const ifBackgroundColor = ifRuleFor('backgroundColor')
export const ifBackground = ifRuleFor('background')
export const ifBorderBottomColor = ifRuleFor('borderBottomColor')
export const ifBorderBottomLeftRadius = ifRuleFor('borderBottomLeftRadius')
export const ifBorderBottomRightRadius = ifRuleFor('borderBottomRightRadius')
export const ifBorderColor = ifRuleFor('borderColor')
export const ifBorderLeftColor = ifRuleFor('borderLeftColor')
export const ifBorderRadius = ifRuleFor('borderRadius')
export const ifBorderRightColor = ifRuleFor('borderRightColor')
export const ifBorderTopColor = ifRuleFor('borderTopColor')
export const ifBorderTopLeftRadius = ifRuleFor('borderTopLeftRadius')
export const ifBorderTopRightRadius = ifRuleFor('borderTopRightRadius')
export const ifBottom = ifRuleFor('bottom')
export const ifCaretColor = ifRuleFor('caretColor')
export const ifColor = ifRuleFor('color')
export const ifFontFamily = ifRuleFor('fontFamily')
export const ifFontSize = ifRuleFor('fontSize')
export const ifFontWeight = ifRuleFor('fontWeight')
export const ifGridGap = ifRuleFor('gridGap')
export const ifGridColumnGap = ifRuleFor('gridColumnGap')
export const ifGridRowGap = ifRuleFor('gridRowGap')
export const ifHeight = ifRuleFor('height')
export const ifLeft = ifRuleFor('left')
export const ifLineHeight = ifRuleFor('lineHeight')
export const ifMarginBottom = ifRuleFor('marginBottom')
export const ifMarginLeft = ifRuleFor('marginLeft')
export const ifMarginRight = ifRuleFor('marginRight')
export const ifMarginTop = ifRuleFor('marginTop')
export const ifMargin = ifRuleFor('margin')
export const ifMaxHeight = ifRuleFor('maxHeight')
export const ifMaxWidth = ifRuleFor('maxWidth')
export const ifMinHeight = ifRuleFor('minHeight')
export const ifMinWidth = ifRuleFor('minWidth')
export const ifOpacity = ifRuleFor('opacity')
export const ifOutlineColor = ifRuleFor('outlineColor')
export const ifPaddingBottom = ifRuleFor('paddingBottom')
export const ifPaddingLeft = ifRuleFor('paddingLeft')
export const ifPaddingRight = ifRuleFor('paddingRight')
export const ifPaddingTop = ifRuleFor('paddingTop')
export const ifPadding = ifRuleFor('padding')
export const ifRight = ifRuleFor('right')
export const ifTop = ifRuleFor('top')
export const ifWidth = ifRuleFor('width')
export const ifZIndex = ifRuleFor('zIndex')
