#!/bin/bash

CMD=$1
shift

exe() { echo "$@" ; $@ ; }

case $CMD in
  clean)
    exe "rm -rf ./dist && rm -rf ./node_modules && yarn cache clean"
    ;;

  build)
    exe "../../node_modules/.bin/rollup -c"
    ;;

  build:watch)
    exe "../../node_modules/.bin/rollup --config --watch"
    ;;

  test)
    exe "../../node_modules/.bin/jest -c $(pwd)/jest.config.js --rootDir ../"
    ;;

  *)
    if [[ -z "$CMD" ]]; then
      echo "USAGE: ./task (clean|build|test|<node_modules_bin_command>) command_args"
      exit 0
    fi
    exe "../../node_modules/.bin/$CMD $@"
    ;;
esac
